### ISSUE TITLE
Not Available for version 3.4.2

### ISSUE THREAD

**Issue by ghost** [deepankardatta/AppleHealthAnalysis#1]
Hello,

I am getting the following error. 

install.packages("applehealthanalysis")
Warning in install.packages :
  package ‘applehealthanalysis’ is not available (for R version 3.4.2)

**Comment by deepankardatta** [comment]
Hi there

I will try and have a look at it today - as this is not my primary job. I haven't updated my version of R yet, but will install 3.4.3 today. I will let you know when I have done this so you can test it.

**Comment by deepankardatta** [comment]
Hi!

Could you give it a try now. The package builds in R 3.4.3.

If you're keen to improve the function some help would be appreciated!

With Thanks

**Comment by deepankardatta** [comment]
Hi

I've updated the package to 0.1.2 to run on R 3.4.3. If you could give it a try it would be great.

What I would do is:

library(AppleHealthAnalysis)
health_data <- ah_import_xml("export.xml")
ah_shiny(health_data)

Let me know what you think.

With Thanks
